version: '3.8'

services:

  client:
    depends_on:
      - balancer
    build:
      context: .
      dockerfile: Client.dockerfile
    deploy :
      mode : replicated
      replicas : ${CLIENT_REPLICAS:-2}
    environment:
      - BALANCER_PORT=${BALANCER_PORT:-3456}
      - SERVER_NAME=balancer

  balancer:
    depends_on:
      - server1
      - server2
      - server3
      - server4
      - server5
    build:
      context: .
      dockerfile: Balancer.dockerfile
    environment:
      - PORT=${BALANCER_PORT:-3456}
      - SERVER_NAME=server
      - SERVER_PORTS=${SERVERS_PORTS:-6455}
      - SERVER_NUM=${SERVERS_NUM:-2}
    ports:
      - "${BALANCER_PORT:-3456}:3456"
  
  server1:
    build:
      context: .
      dockerfile: Server.dockerfile
    environment:
      - "PORT=6455"
  
  server2:
    build:
      context: .
      dockerfile: Server.dockerfile
    environment:
      - "PORT=6456"

  server3:
    build:
      context: .
      dockerfile: Server.dockerfile
    environment:
      - "PORT=6457"

  server4:
    build:
      context: .
      dockerfile: Server.dockerfile
    environment:
      - "PORT=6458"

  server5:
    build:
      context: .
      dockerfile: Server.dockerfile
    environment:
      - "PORT=6459"