// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: src/protobuf/servers.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShortestPathClient is the client API for ShortestPath service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortestPathClient interface {
	SSSP(ctx context.Context, in *Graph, opts ...grpc.CallOption) (*Path, error)
}

type shortestPathClient struct {
	cc grpc.ClientConnInterface
}

func NewShortestPathClient(cc grpc.ClientConnInterface) ShortestPathClient {
	return &shortestPathClient{cc}
}

func (c *shortestPathClient) SSSP(ctx context.Context, in *Graph, opts ...grpc.CallOption) (*Path, error) {
	out := new(Path)
	err := c.cc.Invoke(ctx, "/ShortestPath/SSSP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortestPathServer is the server API for ShortestPath service.
// All implementations must embed UnimplementedShortestPathServer
// for forward compatibility
type ShortestPathServer interface {
	SSSP(context.Context, *Graph) (*Path, error)
	mustEmbedUnimplementedShortestPathServer()
}

// UnimplementedShortestPathServer must be embedded to have forward compatible implementations.
type UnimplementedShortestPathServer struct {
}

func (UnimplementedShortestPathServer) SSSP(context.Context, *Graph) (*Path, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSSP not implemented")
}
func (UnimplementedShortestPathServer) mustEmbedUnimplementedShortestPathServer() {}

// UnsafeShortestPathServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortestPathServer will
// result in compilation errors.
type UnsafeShortestPathServer interface {
	mustEmbedUnimplementedShortestPathServer()
}

func RegisterShortestPathServer(s grpc.ServiceRegistrar, srv ShortestPathServer) {
	s.RegisterService(&ShortestPath_ServiceDesc, srv)
}

func _ShortestPath_SSSP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Graph)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortestPathServer).SSSP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShortestPath/SSSP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortestPathServer).SSSP(ctx, req.(*Graph))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortestPath_ServiceDesc is the grpc.ServiceDesc for ShortestPath service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortestPath_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ShortestPath",
	HandlerType: (*ShortestPathServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SSSP",
			Handler:    _ShortestPath_SSSP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/protobuf/servers.proto",
}
